# This definition is only sourced by 1-prepreprocess_set.R
# Code derived from GIV (Van Wyk de Vries and Wickert, 2021).
matlab_filter_script_code <- c(
  "[A,R]=geotiffread(fullfile(datafolder,fn));",
  "%Orientation filter",
  "filter_1 = [-1 2 -1];",
  "filter_2 = [-1; 2; -1];",
  "filter_3 = [-1 0 0;0 2 0; 0 0 -1];",
  "filter_4 = [0 0 -1;0 2 0; -1 0 0];",
  "filt1 = conv2(A,filter_1,'same');",
  "filt2 = conv2(A,filter_2,'same');",
  "filt3 = conv2(A,filter_3,'same');",
  "filt4 = conv2(A,filter_4,'same');",
  "at1=atan2(filt1,filt2);",
  "at2=atan2(filt3,filt4);",
  "im = cos(at1)+cos(pi()/2-at1)+...",
  "cos(at2)+cos(pi()/2-at2);",
  "% CLAHE filter",
  "in = rescale(im); %Rescale to 0-1, necessary for CLAHE",
  "numberoftiles1=round(size(in,1)/10);",
  "numberoftiles2=round(size(in,2)/10);",
  "if numberoftiles1 < 2",
  "numberoftiles1=2;",
  "end",
  "if numberoftiles2 < 2",
  "numberoftiles2=2;",
  "end",
  "in=adapthisteq(in, 'NumTiles',[numberoftiles1 numberoftiles2], 'ClipLimit', 0.01, 'NBins', 256, 'Range', 'full', 'Distribution', 'uniform');",
  "geotiffwrite(fullfile(outfolder,fn), in, R, 'CoordRefSysCode', 32642)"
) 
